[project]
name = "MI-BCI"
version = "1.0.0"
description = "Brain-Computer Interface (BCI) project"
authors = ["Rokas Bertašius <rokasbertasius33@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64","win-64"]


[tasks]
start = "jupyter lab"

[dependencies]
python = "3.11.*"
pandas = ">=2.2.2,<2.3"
ipykernel = ">=6.29.5,<6.30"
requests = ">=2.32.3,<2.33"
beautifulsoup4 = ">=4.12.3,<4.13"
scipy = ">=1.14.0,<1.15"
tqdm = ">=4.66.4,<4.67"
networkx = ">=3.3,<4"
autoreject = ">=0.4.3,<0.5"
regex = ">=2024.7.24,<2024.8"
jupyter = ">=1.0.0,<1.1"
cupy = ">=13.3.0,<13.4"
pytest = ">=8.3.2,<8.4"
pyprep = ">=0.4.3,<0.5"
joblib = ">=1.4.2,<1.5"
pillow = ">=10.4.0,<10.5"
seaborn = ">=0.13.2,<0.14"
ruff = ">=0.6.4,<0.7"
pyriemann = ">=0.7,<0.8"
xgboost = ">=2.1.1,<3"
numpy = ">=2.1.2,<3"
keras = ">=3.6.0,<4"



[pypi-dependencies]
mne = "*"
pyqt5 = "*"

